# Repo: Contoso/WindowsProduct
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: github
      name: Contoso/BuildTemplates
      endpoint: sathishsuresh1
      

jobs:
- template: common.yml@templates  # Template reference
  parameters:
    vmImage: 'windows-latest'
